### ISSUE TITLE
 BAR1 Size Limited to 256MB on 8x NVIDIA 4090 Workstation

### ISSUE THREAD

**Issue by histfuture** [tinygrad/open-gpu-kernel-modules#19]
### NVIDIA Open GPU Kernel Modules Version

550.90.07

### Please confirm this issue does not happen with the proprietary driver (of the same version). This issue tracker is only for bugs specific to the open kernel driver.

- [X] I confirm that this does not happen with the proprietary driver package.

### Operating System and Version

Ubuntu 20.04.6 LTS

### Kernel Release

Linux gpus10-SYS-420GP-TNR 5.15.0-97-generic #107~20.04.1-Ubuntu SMP Fri Feb 9 14:20:11 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Please confirm you are running a stable release kernel (e.g. not a -rc). We do not accept bug reports for unreleased kernels.

- [X] I am running on a stable kernel release.

### Hardware: GPU

4090

### Describe the bug

Hi,

I have a workstation with 8x NVIDIA 4090 GPUs. The system is running NVIDIA driver version **550.90.07**. Below is the relevant output from lspci:
 
52:00.0 VGA compatible controller: NVIDIA Corporation Device 2684 (rev a1) (prog-if 00 [VGA controller])
    Subsystem: NVIDIA Corporation Device 167c
    Flags: bus master, fast devsel, latency 0, IRQ 311, NUMA node 0
    Memory at b8000000 (32-bit, non-prefetchable) [size=16M]
    Memory at 10ffc0000000 (64-bit, prefetchable) [size=256M]
    Memory at 10ffb8000000 (64-bit, prefetchable) [size=32M]

I noticed that my BAR1 memory is only 256MB. However, on other systems, I've seen BAR1 sizes as large as 32GB.

Additionally, my BIOS does not have a "Resizable BAR" setting. However, there is an option for "Above 4G Decoding," which I have enabled.

Could you please help me understand why the BAR1 size is limited to 256MB and if there is anything I can do to increase it?

Thanks!

### To Reproduce

NULL

### Bug Incidence

Always

### nvidia-bug-report.log.gz

[nvidia-bug-report.log.gz](https://github.com/user-attachments/files/17362257/nvidia-bug-report.log.gz)

**Comment by zL1nX** [comment]
Hello, I also encountered this issue on the similar settings. 

```
01:00.0 VGA compatible controller: NVIDIA Corporation Device 2684 (rev a1) (prog-if 00 [VGA controller])
	Subsystem: NVIDIA Corporation Device 16f3
	Flags: bus master, fast devsel, latency 0, IRQ 727, NUMA node 0, IOMMU group 70
	Memory at f8000000 (32-bit, non-prefetchable) [size=16M]
	Memory at 4bde0000000 (64-bit, prefetchable) [size=256M]
	Memory at 4bdf0000000 (64-bit, prefetchable) [size=32M]
	I/O ports at 1000 [size=128]
	Expansion ROM at f9000000 [virtual] [disabled] [size=512K]
	Capabilities: <access denied>
	Kernel driver in use: nvidia
	Kernel modules: nvidiafb, nouveau, nvidia_drm, nvidia
```

My server:
- CPU: AMD EPYC 7763
- GPU: 8x4090 (2684)
- No PCIe switch chip in the middle (e.g. PEX). Four cards are directly passed through to one CPU.

Is there any fix now? Thanks.

**Comment by mylesgoose** [comment]
@zL1nX what bios are you using? My bios gave no option for that and then updating it enabled that option. Was an ami bios.

**Comment by zL1nX** [comment]
Hi! The bios in my server is from ASUS. At first, it does not present the option of adjusting the BAR size. 
By your suggestion, I checked its user guide again. It turns out that I need to first disable the Compatibility Support Module (CSM) option. Thanks for the advice.

**Comment by mylesgoose** [comment]
@zL1nX nice..

**Comment by histfuture** [comment]
After some exploration, I found that the issue is caused by BIOS support for Resize Bar. For newer BIOS versions, it can be resolved by enabling 'Resize Bar' in the BIOS settings. For older BIOS versions, the problem can be addressed using this project: [ReBarUEFI](https://github.com/xCuri0/ReBarUEFI).

hope this helps.
