### ISSUE TITLE
Modified successfully, but not displayed on ALLTOALL?

### ISSUE THREAD

**Issue by yiguCM** [tinygrad/open-gpu-kernel-modules#24]
### NVIDIA Open GPU Kernel Modules Version

550.90.07-p2p

### Please confirm this issue does not happen with the proprietary driver (of the same version). This issue tracker is only for bugs specific to the open kernel driver.

- [X] I confirm that this does not happen with the proprietary driver package.

### Operating System and Version

Ubuntu 22.04.5 LTS

### Kernel Release

Linux 6.8.0-47-generic #47~22.04.1-Ubuntu

### Please confirm you are running a stable release kernel (e.g. not a -rc). We do not accept bug reports for unreleased kernels.

- [X] I am running on a stable kernel release.

### Hardware: GPU

GPU 0: NVIDIA GeForce RTX 4090 ~ GPU 7: NVIDIA GeForce RTX 4090

### Describe the bug

I successfully modified BAR1 and enabled the P2P function, which increased the performance of P2PTEST, but when I performed the NCCL test, I found that the performance of ALL TO ALL scenarios decreased. Why is this?
Is it because the BAR1 register is too large? Can we only open P2P and not modify BAR1?
![image](https://github.com/user-attachments/assets/a7334b6d-b123-49f2-a4e6-9fd26a42796b)
![image](https://github.com/user-attachments/assets/edec96b0-f6d8-4a9c-8d35-e94b966b001e)

### To Reproduce

/nccl-tests/build/alltoall_perf -b 8 -e 8G -f 2 -g 8

### Bug Incidence

Always

### nvidia-bug-report.log.gz

![image](https://github.com/user-attachments/assets/a7334b6d-b123-49f2-a4e6-9fd26a42796b)
![image](https://github.com/user-attachments/assets/edec96b0-f6d8-4a9c-8d35-e94b966b001e)
![image](https://github.com/user-attachments/assets/ad448a9c-82b5-4570-840d-c6edd7552a9e)

**Comment by xiaobuding-cx** [comment]
Hi, is there anything changed?
